### PR TITLE
Choose which cross-origin URL to use up front.

### LINKED ISSUE #3076: Image loading tests have become flaky after #3052
#3052 seems to have introduced significant flakiness into the tests which load cross-origin images. On Chromium's automated testing system, the following bugs have been found:

WebGL origin-clean-conformance-* test fail because image loading failed
http://crbug.com/1082525

conformance/textures/misc/origin-clean-conformance.html is flaky
http://crbug.com/1083100

@jdashg @shrekshao @jdarpinian how can we fix this flakiness? In hindsight, 1000 ms is too short a timeout for some slow bots.

### PR DESCRIPTION
**Pull request by kenrussell**
The earliest version of this code, which was seemingly stable, made the
determination of whether to use a local or remote URL cor cross-origin
images up front.  Network timeouts from machines that deliberately
aren't connected to the open Internet can't be relied upon as a fallback
mechanism. Change the code back to examine the test's URL and choose
whether to load local or remote images based on that. Also attempt to
make runningOnLocalhost more robust to IPv6 loopback addresses.

Follow-on to #3052 and #3077. See http://crbug.com/1082525 for more
background.

Should fix #3076 conclusively.

Note that #3097 was proposed as an alternative solution for this problem
and may still be considered in the future if this change destabilizes some
browsers' CI systems.

### CODE REVIEW

**Comment by kenrussell** [comment]
@jdashg @shrekshao please review. It's been found by both Google and Intel that the fallback that was added in #3052 doesn't work on our automated test setups.

Tested this locally and verified that the local invocations now use the localhost URL.

@gyagp FYI.

**Comment by gyagp** [comment]
Related cases can also pass now with this fix at my side.

File: sdk/tests/js/webgl-test-utils.js [hunk 1]
```diff
@@ -3183,13 +3183,16 @@ var getBaseDomain = function(host) {
 }
 
 var runningOnLocalhost = function() {
-  return window.location.hostname.indexOf("localhost") != -1 ||
-      window.location.hostname.indexOf("127.0.0.1") != -1;
+  let hostname = window.location.hostname;
+  return hostname.indexOf("localhost") != -1 ||
+    hostname.indexOf("127.0.0.1") != -1 ||
+    hostname.indexOf("::1") != -1;
```
Comment (kainino0x) [inline sdk/tests/js/webgl-test-utils.js:3189]: not sure indexOf is technically the right choice here; why not just use `===` for all of these? I doubt it would come up, but you wouldn't want to match `xxxx:xxxx:xxxx::1`.

Comment (kenrussell) [reply sdk/tests/js/webgl-test-utils.js]: Good point - not sure why the code was written this way originally. Done.

**Comment by kenrussell** [comment]
Thanks for all of your reviews. Merging now.
